<?php

/**
 * @file
 * module file 
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 * form - 'user_admin_settings' 
 */
function user_pwreset_timeout_form_user_admin_settings_alter(array &$form, FormStateInterface $form_state) {
  $config = \Drupal::configFactory()->getEditable('user.settings');

  $form['password_timeout_settings'] = array(
    '#type' => 'details',
    '#title' => t('Password reset timeout'),
    '#open' => TRUE,
    '#weight' => 0,
  );
  $form['password_timeout_settings']['password_reset_timeout'] = [
    '#type' => 'number',
    '#min' => 1,
    '#max' => 31536000,
    '#title' => t('Password Reset Timeout'),
    '#description' => t('Set the timeout in seconds for one-time login links. The default is 86400 seconds (24 hours).'),
    '#default_value' => $config->get('password_reset_timeout', 86400),
  ];

  $form['#submit'][] = 'user_pwreset_timeout_user_admin_settings_submit';
}

/**
 * Submit handler for the user_admin_settings form.
 *
 * @param array $form
 * @param FormStateInterface $form_state 
 */
function user_pwreset_timeout_user_admin_settings_submit(array $form, FormStateInterface $form_state) {
  $timeout_value = $form_state->getValue('password_reset_timeout');
  $config = \Drupal::configFactory()->getEditable('user.settings');
  $config->set('password_reset_timeout', $timeout_value)->save();
}
